import { getMistral } from "../config/llm.js";
import { uploadToS3 } from "../config/s3.js";
import { PDFDocument, rgb, StandardFonts } from "pdf-lib";

export const pdfAgent = async (state) => {
  const prompt = state.prompt || "";
  let content = "";
  try {
    const mistral = getMistral();
    if (mistral) {
      const res = await mistral.chat.complete({
        model: "mistral-small-latest",
        messages: [{ role: "user", content: `You are a PDF agent. Create markdown content for a PDF about: ${prompt}. Include title, sections, bullet points.` }],
        maxTokens: 700,
      });
      content = res.choices?.[0]?.message?.content || `[pdf] ${prompt}`;
    } else {
      content = `[pdf] PDF content for: ${prompt} (stub)`;
    }
  } catch (e) {
    console.warn("pdf mistral failed:", e.message);
    content = `[pdf] PDF content for: ${prompt} (stub)`;
  }
  // Generate real PDF with pdf-lib + watermark
  try {
    const pdfDoc = await PDFDocument.create();
    const page = pdfDoc.addPage([595, 842]); // A4
    const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const watermark = "Generated by Cortex AI";
    // Title
    page.drawText(prompt.slice(0,60), { x: 50, y: 780, size: 16, font: fontBold, color: rgb(0.2,0.2,0.8) });
    // Content (simple, split lines)
    // Sanitize for WinAnsi: Helvetica only supports Latin-1, strip emojis/non-ASCII
    const sanitized = content.replace(/[^\x00-\x7F]/g, "").replace(/✅|📄|—|–|•/g, "");
    const lines = sanitized.split("\n").slice(0, 40);
    let y = 750;
    for (const line of lines) {
      if (y < 50) break;
      try {
        page.drawText(line.slice(0,90), { x: 50, y, size: 9, font, color: rgb(0,0,0) });
      } catch {}
      y -= 12;
    }
    // Watermark footer
    page.drawText(watermark, { x: 200, y: 20, size: 8, font, color: rgb(0.5,0.5,0.5), opacity: 0.5 });
    const pdfBytes = await pdfDoc.save();
    const key = `pdfs/${Date.now()}-${prompt.slice(0,20).replace(/\W/g, "_")}.pdf`;
    console.log(`[pdf] uploading ${key} to S3`);
    const url = await uploadToS3(key, Buffer.from(pdfBytes), "application/pdf");
    console.log(`[pdf] S3 url: ${url}`);
    return { aiResponse: `${content}\n\n---\n📄 PDF generated (${pdfBytes.length} bytes): ${url}\nWatermark: Generated by Cortex AI | [Download PDF](${url})` };
  } catch (e) {
    console.warn("pdf gen failed:", e.message, e.stack?.slice(0,500));
    return { aiResponse: content };
  }
};
