import pptxgen from "pptxgenjs";

export const generatePpt = async (data) => {
  const ppt = new pptxgen();
  ppt.layout = "LAYOUT_WIDE";
  ppt.author = "Cortex AI";
  ppt.title = data.title || "Cortex AI Presentation";
  ppt.subject = data.title || "Cortex AI";
  ppt.company = "Cortex AI";
  ppt.lang = "en-US";
  ppt.theme = { headFontFace: "Aptos", bodyFontFace: "Aptos" };

  const addCover = (ppt, data) => {
    const slide = ppt.addSlide();
    slide.addText(data.title || "Cortex AI", { x: 1, y: 2, w: 8, h: 1, fontSize: 28, bold: true, color: "003366", align: "center" });
    slide.addText(data.subtitle || "Generated by Cortex AI", { x: 1, y: 3, w: 8, h: 0.5, fontSize: 14, color: "666666", align: "center" });
  };

  const addContentSlide = (ppt, title, points, num, total) => {
    const slide = ppt.addSlide();
    slide.addText(title, { x: 0.5, y: 0.3, w: 9, h: 0.6, fontSize: 18, bold: true, color: "003366" });
    points.forEach((p, i) => {
      slide.addText(`• ${p}`, { x: 0.5, y: 1.0 + i * 0.4, w: 9, h: 0.3, fontSize: 11, color: "333333" });
    });
    slide.addText(`${num}/${total}`, { x: 9, y: 5.3, w: 1, h: 0.2, fontSize: 8, color: "999999", align: "right" });
  };

  const addThankYou = (ppt) => {
    const slide = ppt.addSlide();
    slide.addText("Thank You", { x: 1, y: 2.5, w: 8, h: 1, fontSize: 32, bold: true, color: "003366", align: "center" });
    slide.addText("Generated by Cortex AI", { x: 1, y: 3.5, w: 8, h: 0.5, fontSize: 12, color: "666666", align: "center" });
  };

  addCover(ppt, data);
  (data.slides || []).forEach((s, i) => addContentSlide(ppt, s.title, s.points, i + 1, data.slides.length));
  addThankYou(ppt);

  return ppt;
};
